// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZmFVHYvucKZKNlLbBhTXR7N_-kn5aYVg',
    appId: '1:924746589221:web:a7afb8faa4c505bcb24bcc',
    messagingSenderId: '924746589221',
    projectId: 'abdullahi-sow-project',
    authDomain: 'abdullahi-sow-project.firebaseapp.com',
    storageBucket: 'abdullahi-sow-project.firebasestorage.app',
    measurementId: 'G-2DYS8FNY4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb8Uj3-HqjkfnnPApOkcC5Hybl10u4nx0',
    appId: '1:924746589221:android:57932e6fd92e0bdeb24bcc',
    messagingSenderId: '924746589221',
    projectId: 'abdullahi-sow-project',
    storageBucket: 'abdullahi-sow-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCABOADAM_uMtE250P9JykwS_PrMUvewmw',
    appId: '1:924746589221:ios:2b03e76f1448348ab24bcc',
    messagingSenderId: '924746589221',
    projectId: 'abdullahi-sow-project',
    storageBucket: 'abdullahi-sow-project.firebasestorage.app',
    iosBundleId: 'com.autosales.corp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCABOADAM_uMtE250P9JykwS_PrMUvewmw',
    appId: '1:924746589221:ios:ea7e35d5789c30e4b24bcc',
    messagingSenderId: '924746589221',
    projectId: 'abdullahi-sow-project',
    storageBucket: 'abdullahi-sow-project.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZmFVHYvucKZKNlLbBhTXR7N_-kn5aYVg',
    appId: '1:924746589221:web:5480d8ed7f403e3ab24bcc',
    messagingSenderId: '924746589221',
    projectId: 'abdullahi-sow-project',
    authDomain: 'abdullahi-sow-project.firebaseapp.com',
    storageBucket: 'abdullahi-sow-project.firebasestorage.app',
    measurementId: 'G-2BNYEGEBR8',
  );

}