// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrRDTd5w2iWxTIfvsn7ra0xjW7M-iuPN8',
    appId: '1:577373430777:web:5af70db59c5d49a8125328',
    messagingSenderId: '577373430777',
    projectId: 'car-selling-flutter-app',
    authDomain: 'car-selling-flutter-app.firebaseapp.com',
    storageBucket: 'car-selling-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_dXN5QsR1Dxob1ex8I4y4sXQRGIOah3k',
    appId: '1:577373430777:android:9a27a422f3d043b6125328',
    messagingSenderId: '577373430777',
    projectId: 'car-selling-flutter-app',
    storageBucket: 'car-selling-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABrxCtLot_sX3uXoBxjVmPXa2lrRylo3Y',
    appId: '1:577373430777:ios:c424208e88aeb2e7125328',
    messagingSenderId: '577373430777',
    projectId: 'car-selling-flutter-app',
    storageBucket: 'car-selling-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABrxCtLot_sX3uXoBxjVmPXa2lrRylo3Y',
    appId: '1:577373430777:ios:796aa32cd6a07256125328',
    messagingSenderId: '577373430777',
    projectId: 'car-selling-flutter-app',
    storageBucket: 'car-selling-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp.RunnerTests',
  );
}
